=== Rayaxe2/SemiDataCW2/Labs/xml-lab-solutions/xml-lab-solutions/person.xsd
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema'>

<xs:element name="person">
 <xs:complexType>
 <xs:sequence>
  <xs:element ref="name"/>
  <xs:element ref="birth"/>
  <xs:element ref="death"/>
  <xs:element ref="profession" minOccurs='1' maxOccurs='unbounded'/>
 </xs:sequence>
  <xs:attribute name="id" type="xs:string"/>
 </xs:complexType>
</xs:element>

 <xs:element name="name">
 	<xs:complexType>
		 <xs:sequence>
 			<xs:element ref="first"/>
 			<xs:element ref="last"/>
 		</xs:sequence>
 	</xs:complexType>
 </xs:element>

 <xs:element name="first" type='xs:string'/>
 <xs:element name="last" type='xs:string'/>
 <xs:element name="birth" type='xs:date'/>
 <xs:element name="death" type='xs:date'/>
 <xs:element name="profession" type='xs:string'/>
</xs:schema>

=== Rayaxe2/SemiDataCW2/Labs/xml-lab-solutions/xml-lab-solutions/turing2.xml
<?xml version="1.0" encoding="UTF-8"?>
<person xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="person.xsd" id="turing">
	<name>
		<first>Alan</first>
		<last>Turing</last>
	</name>
	<birth>2001-01-01</birth>
	<death>2001-01-01</death>
	<profession>Computer Scientist</profession>
	<profession>Mathematician</profession>
	<profession>Crypographer</profession>
</person>
